// SPDX-FileCopyrightText: Copyright 2024 Prasad Tengse
// SPDX-License-Identifier: MIT
//
// This file is automatically generated by go run generate.go -output .
// DO NOT EDIT THIS FILE.

//go:build darwin

package macos

//go:cgo_import_dynamic CoreFoundation_CFRelease CFRelease "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//nolint:revive,stylecheck // ignore
var cf_trampoline_release_addr uintptr

//go:cgo_import_dynamic CoreFoundation_CFArrayGetCount CFArrayGetCount "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
//nolint:revive,stylecheck // ignore
var cf_trampoline_array_get_count_addr uintptr

