version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - "dependabot"
      - "dependencies"
      - "dep/actions"
      - "luna/autoupdate"
    commit-message:
      prefix: "chore(deps):"
    schedule:
      interval: "weekly"
      day: "saturday"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: gomod
    directory: /
    labels:
      - "dependabot"
      - "dependencies"
      - "dep/go"
      - "luna/autoupdate"
    commit-message:
      prefix: "chore(deps):"
    schedule:
      interval: "weekly"
      day: "saturday"
    pull-request-branch-name:
      separator: "-"
