# SPDX-FileCopyrightText: Copyright 2023 Prasad Tengse.
# SPDX-License-Identifier: MIT

run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 3m

# This file contains only configs which differ from defaults.
# All possible options can be found here
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 35
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 0

  gocyclo:
    min-complexity: 35

  dupl:
    threshold: 200

  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
    # Lint about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    # Default: false
    check-blank: false
    exclude-functions:
      - bytes/Buffer.Write
      - bytes/Buffer.WriteByte
      - bytes/Buffer.WriteString
      - strings/Builder.WriteString
      - strings/Builder.Write
      - strings/Builder.WriteRune
      - crypto/Hash.Write
      - io/Discard.Write
      - os/Stderr.Write
      - os/Stdout.Write

  exhaustive:
    # Program elements to check for exhaustiveness.
    # Default: [ switch ]
    check:
      - switch
      - map
    # Presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed.
    default-signifies-exhaustive: true

  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 150
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: 100

  gocognit:
    # Minimal code complexity to report
    min-complexity: 30

  goconst:
    match-constant: true
    min-len: 3
    min-occurrences: 9
    ignore-tests: true
    ignore-calls: true
    numbers: false

  gocritic:
    # Settings passed to gocritic.
    # The settings key is the name of a supported gocritic checker.
    # The list of supported checkers can be find in https://go-critic.github.io/overview.
    settings:
      captLocal:
        # Whether to restrict checker to params only.
        # Default: true
        paramsOnly: false
      underef:
        # Whether to skip (*x).method() calls where x is a pointer receiver.
        # Default: true
        skipRecvDeref: false

  goheader:
    # Supports two types 'const` and `regexp`.
    # Values can be used recursively.
    # Default: {}
    values:
      regexp:
        # Define here regexp type values.
        # for example:
        license: "(BSD\\-3\\-Clause|GPL\\-3\\.0\\-only|GPL\\-2.0\\-only|AGPL\\-3\\.0\\-only|Apache\\-2\\.0|MIT|MPL\\-2.0)"
        copyright: "([Cc]opyright\\s+((\\(c\\)|©)\\s+)?[0-9]{4}(.*))"
    template: |-
      SPDX-FileCopyrightText: {{ copyright }}
      SPDX-License-Identifier: {{ license }}

  gomodguard:
    blocked:
      # List of blocked modules.
      # Default: []
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
            reason: "See https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules"

        # Use stdlib replacements.
        - github.com/mitchellh/go-homedir:
            reason: "Use stdlib provided os.UserHomeDir()."
        - github.com/hashicorp/go-multierror:
            reason: "Use stdlib provided errors.Join() available in go 1.20."
        - go.uber.org/multierr:
            reason: "Use stdlib provided errors.Join() available in go 1.20."
        - github.com/hashicorp/go-hclog:
            reason: "Use log/slog or github.com/tprasadtp/log package."
        - github.com/rs/zerolog:
            reason: "Use log/slog or github.com/tprasadtp/log package."
        - github.com/sirupsen/logrus:
            reason: "Use log/slog or github.com/tprasadtp/log package."
        - go.uber.org/zap:
            reason: "Use log/slog or github.com/tprasadtp/log package."
        - github.com/pkg/errors:
            reason: "Use error wrapping available in stdlib"

        # Hashicorp has changed their license to BUSL for most products.
        # Avoid them. Libraries may not be under BUSL,
        # but they directly or indirectly depend on BUSL licensed product.
        # --------------------------------------------------------------------

        # Hashicorp Terraform
        - github.com/hashicorp/terraform-plugin-sdk:
            reason: "Hashicorp terraform is no longer open source."
        - github.com/hashicorp/terraform-cdk-go/cdktf:
            reason: "Hashicorp terraform is no longer open source."
        - github.com/hashicorp/go-tfe:
            reason: "Hashicorp terraform is no longer open source."
        - hashicorp/terraform-plugin-log:
            reason: "Hashicorp terraform is no longer open source."

        # Hashicorp Vault
        - github.com/hashicorp/vault-client-go:
            reason: "Hashicorp vault is no longer open source."
        - github.com/hashicorp/vault/sdk:
            reason: "Hashicorp vault is no longer open source."
        - github.com/hashicorp/vault/api:
            reason: "hashicorp vault is no longer open source."
        - github.com/hashicorp/vault:
            reason: "hashicorp vault is no longer open source."

        # Hashicorp Consul
        - github.com/hashicorp/consul/api:
            reason: "Hashicorp consul is no longer open source."

        # Hashicorp Nomad
        - github.com/hashicorp/nomad/api:
            reason: "Hashicorp nomad is no longer open source."

        # Hashicorp Boundary
        - github.com/hashicorp/boundary/api:
            reason: "Hashicorp boundary is no longer open source."
        - github.com/hashicorp/boundary/sdk:
            reason: "Hashicorp boundary is no longer open source."
        - github.com/hashicorp/boundary/plugins:
            reason: "Hashicorp boundary is no longer open source."

        # Hashicorp Packer
        - github.com/hashicorp/packer-plugin-sdk:
            reason: "Hashicorp packer is no longer open source."

        # Elastic has changed their license to SSPL/ELv2 which is not
        # open source for most of their products. Avoid them. Libraries
        # may be under open source license, but they directly or indirectly
        # depend on SSPL licensed product.
        # --------------------------------------------------------------------

        # Elastic libbeat/beats
        - github.com/elastic/beats/libbeat:
            reason: "Elastic beats is not open source."
        - github.com/elastic/beats/v7/libbeat:
            reason: "Elastic beats is not open source."

  forbidigo:
    # Forbid the following identifiers (list of regexp).
    # Default: ["^(fmt\\.Print(|f|ln)|print|println)$"]
    forbid:
      # Builtin function:
      - p: ^print.*$
        msg: "Do not commit print builtin statements."

      # fmt.Prinf|Println
      - p: "fmt.Print(f|ln)?(.*)"
        msg: "Do not commit print statements."

      - p: "fmt.Fprint(f|ln)?\\(os.Std(out|err)(.*)"
        msg: "Do not commit print statements."

      # [Disabled] Too many false positives for tests.
      # - p: time.Sleep
      #   msg: "Avoid using time.Sleep in you code."

      - p: 'log.KV\(log\.ErrorKey\s+,.*'
        msg: "Use log.E(error) instead"

    # Exclude godoc examples from forbidigo checks.
    # Default: true
    exclude-godoc-examples: true
    # Instead of matching the literal source code,
    # use type information to replace expressions with strings that contain the package name
    # and (for methods and fields) the type name.
    # This makes it possible to handle import renaming and forbid struct fields and methods.
    # Default: false
    analyze-types: true

  govet:
    # Enable all analyzers.
    # Default: false
    enable-all: true
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    # Default: []
    disable:
      - fieldalignment # too strict
    # Settings per analyzer.
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        # Default: false
        strict: true

  ireturn:
    # Only allow error, stdlib, empty and generic interfaces.
    # Default: [errors, empty, stdlib, anon]
    allow:
      - error # error interface
      - empty # interface{} or any
      - stdlib # interfaces in stdlib
      - generic # generic interfaces added in go 1.18 (type constraints)

  nakedret:
    # Make an issue if func has more lines of code than this setting, and it has naked returns.
    # Default: 30
    max-func-lines: 0

  nestif:
    # [Default: 5]
    min-complexity: 8

  nolintlint:
    # Exclude following linters from requiring an explanation.
    # Default: []
    allow-no-explanation:
      - cyclop
      - errcheck
      - funlen
      - gochecknoglobals
      - gocognit
      - gocyclo
      - lll
      - nestif
    # Enable to require an explanation of nonzero length after each nolint directive.
    # Default: false
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed.
    # Default: false
    require-specific: true

  sloglint:
    # Enforce using attributes only (incompatible with kv-only).
    # Default: false
    attr-only: true

  tenv:
    # The option `all` will run against whole test files
    # (`_test.go`) regardless of method/function signatures.
    # Otherwise, only methods that take `*testing.T`, `*testing.B`,
    # and `testing.TB` as arguments are checked.
    # Default: false
    all: true

  thelper:
    test:
      # Check t.Helper() begins helper function.
      # Default: true
      begin: false
    benchmark:
      # Check b.Helper() begins helper function.
      # Default: true
      begin: false
    tb:
      # Check tb.Helper() begins helper function.
      # Default: true
      begin: false
    fuzz:
      # Check f.Helper() begins helper function.
      # Default: true
      begin: false

linters:
  disable-all: true
  enable:
    ## Enabled by default
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - gosimple # specializes in simplifying a code
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # detects when assignments to existing variables are not used
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    - typecheck # like the front-end of a Go compiler, parses and type-checks Go code
    - unused # checks for unused constants, variables, functions and types

    ## Disabled by default
    - asasalint # checks for pass []any as any in variadic func(...any)
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - bodyclose # checks whether HTTP response body is closed successfully
    - cyclop # checks function and package cyclomatic complexity
    - dupl # tool for code clone detection
    - durationcheck # checks for two durations multiplied together
    - errname # checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error
    - errorlint # finds code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - execinquery # checks query string in Query function which reads your Go src files and warning it finds
    - exhaustive # checks exhaustiveness of enum switch statements
    - exportloopref # checks for pointers to enclosing loop variables
    - forbidigo # forbids identifiers
    - funlen # tool for detection of long functions
    - gochecknoinits # checks that no init functions are present in Go code
    - gocognit # computes and checks the cognitive complexity of functions
    - goconst # finds repeated strings that could be replaced by a constant
    - gocritic # provides diagnostics that check for bugs, performance and style issues
    - gocyclo # computes and checks the cyclomatic complexity of functions
    - godot # checks if comments end in a period
    - goimports # in addition to fixing imports, goimports also formats your code in the same style as gofmt
    - gomoddirectives # manages the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - gomodguard # allow and block lists linter for direct Go module dependencies.
    - goprintffuncname # checks that printf-like functions are named with f at the end
    - gosec # inspects source code for security problems
    - makezero # finds slice declarations with non-zero initial length
    - nakedret # finds naked returns in functions greater than a specified function length
    - nestif # reports deeply nested if statements
    - nilerr # finds the code that returns nil even if it checks that the error is not nil
    - nilnil # checks that there is no simultaneous return of nil error and an invalid value
    - noctx # finds sending http request without context.Context
    - nolintlint # reports ill-formed or insufficient nolint directives
    - nonamedreturns # reports all named returns
    - nosprintfhostport # checks for misuse of Sprintf to construct a host with port in a URL
    - predeclared # finds code that shadows one of Go's predeclared identifiers
    - promlinter # checks Prometheus metrics naming via promlint
    - reassign # checks that package variables are not reassigned
    - revive # fast, configurable, extensible, flexible, and beautiful linter
    - rowserrcheck # checks whether Err of rows is checked successfully
    - sqlclosecheck # checks that sql.Rows and sql.Stmt are closed
    - stylecheck # is a replacement for golint
    - sloglint # lint log/slog usage
    - tenv # detects using os.Setenv instead of t.Setenv since Go1.17
    - tparallel # detects inappropriate usage of t.Parallel() method in your Go test codes
    - unconvert # removes unnecessary type conversions
    - unparam # reports unused function parameters
    - usestdlibvars # detects the possibility to use variables/constants from the Go standard library
    - wastedassign # finds wasted assignment statements
    - whitespace # detects leading and trailing whitespace
    - decorder # checks declaration order and count of types, constants, variables and functions
    - prealloc #  finds slice declarations that could potentially be preallocated
    - interfacebloat # checks the number of methods inside an interface
    - wrapcheck # checks that errors returned from external packages are wrapped
    - loggercheck # checks key value pairs for common logger libraries (kitlog,klog,logr,zap)
    - importas # enforces consistent import aliases
    - testableexamples # checks if examples are testable (have an expected output)
    - goheader # checks for headers
    - containedctx # detects struct contained context.Context field
    - thelper # detects golang test helpers without t.Helper() call and checks the consistency of test helpers

    ## you may want to enable
    #- godox # detects FIXME, TODO and other comment keywords

    ## disabled
    #- gci # [conflicts with vscode gofumpt] controls golang package import order and makes it always deterministic
    #- gomnd # [too noisy] detects magic numbers
    #- lll # [mostly useless] reports long lines
    #- exhaustruct # [mostly useless] checks if all structure fields are initialized
    #- gochecknoglobals # [useless, unless you are a beginner] checks that no global variables exist
    #- contextcheck # [too many false positives] checks the function whether use a non-inherited context
    #- depguard # [replaced by gomodguard] checks if package imports are in a list of acceptable packages
    #- dogsled # checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    #- dupword # [useless without config] checks for duplicate words in the source code
    #- forcetypeassert # [replaced by errcheck] finds forced type assertions
    #- goerr113 # [too strict] checks the errors handling expressions
    #- gofmt # [replaced by goimports] checks whether code was gofmt-ed
    #- gofumpt # [replaced by goimports, gofumports is not available yet] checks whether code was gofumpt-ed
    #- grouper # analyzes expression groups
    #- maintidx # measures the maintainability index of each function
    #- misspell # [useless] finds commonly misspelled English words in comments
    #- nlreturn # [too strict and mostly code is not more readable] checks for a new line before return and branch statements to increase code clarity
    #- paralleltest # [too many false positives] detects missing usage of t.Parallel() method in your Go test
    #- tagliatelle # checks the struct tags
    #- wsl # [too strict and mostly code is not more readable] whitespace linter forces you to use empty lines
    #- varnamelen [too noisy] # checks that the length of a variable's name matches its scope
    #- ireturn # [useless as we use functional options with interfaces a lot] accept interfaces, return concrete types (with stdlib interfaces ignored)

    ## deprecated
    #- deadcode # [deprecated, replaced by unused] finds unused code
    #- exhaustivestruct # [deprecated, replaced by exhaustruct] checks if all struct's fields are initialized
    #- golint # [deprecated, replaced by revive] golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes
    #- ifshort # [deprecated] checks that your code uses short syntax for if-statements whenever possible
    #- interfacer # [deprecated] suggests narrower interface types
    #- maligned # [deprecated, replaced by govet fieldalignment] detects Go structs that would take less memory if their fields were sorted
    #- nosnakecase # [deprecated, replaced by revive var-naming] detects snake case of variable naming and function name
    #- scopelint # [deprecated, replaced by exportloopref] checks for unpinned variables in go programs
    #- structcheck # [deprecated, replaced by unused] finds unused struct fields
    #- varcheck # [deprecated, replaced by unused] finds unused global variables and constants

issues:
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 50
  exclude-rules:
    # It is mostly okay to shadow err. ineffassign will warn,
    # if error checking is not done immediately. However,
    # same MUST NOT be done for ctx as context is a "container".
    - linters:
        - govet
      text: 'shadow: declaration of "err" shadows declaration at'

    # Ignore long lines for go generate.
    - source: "^//\\s*go:generate\\s"
      linters:
        - lll

    # Ignore TODO.
    - source: "(noinspection|TODO)"
      linters:
        - godot

    # Test might add more checks to the else branch and keep them uniform
    # across all test cases. This also improves test code readability.
    - path: '(.+)_test\.go'
      text: "elseif: can replace 'else {if cond {}}' with 'else if cond {}'"

    # Disable some linters for testing code.
    - path: '(.+)_test\.go'
      linters:
        - dupl
        - nestif
        - funlen
        - cyclop
        - goconst
        - gocyclo
        - gocognit
        - wrapcheck
        - containedctx

    # Disable some linters for generated code.
    - path: 'testdata\.go'
      linters:
        - funlen
        - gocyclo
        - goconst
        - gocyclo
        - gocognit
        - wrapcheck

    # Disable some linters for ad-hoc scripts and example scripts.
    - path: '(example|generate)\.go'
      linters:
        - wrapcheck
        - forbidigo
