// Code generated by "stringer -type=Kind -output value_kind_string.go -trimprefix=Kind"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindAny-0]
	_ = x[KindBool-1]
	_ = x[KindString-2]
	_ = x[KindInt64-3]
	_ = x[KindUint64-4]
	_ = x[KindFloat64-5]
	_ = x[KindComplex128-6]
	_ = x[KindDuration-7]
	_ = x[KindTime-8]
	_ = x[KindIPAddr-9]
	_ = x[KindIPPrefix-10]
}

const _Kind_name = "AnyBoolStringInt64Uint64Float64Complex128DurationTimeIPAddrIPPrefix"

var _Kind_index = [...]uint8{0, 3, 7, 13, 18, 24, 31, 41, 49, 53, 59, 67}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
