.\"                              DO NOT EDIT
.\" --------------------------------------------------------------------------
.\" This manpage is automatically generated by github.com/tprasadtp/pkg/cli.
.\" --------------------------------------------------------------------------
.TH "{{ .Root.Name | upper }}" 1 "{{ "2 Jan 2006" | formatGeneratedAt }}" "{{.Version}}" "User Manual for {{ .Root.Name | title }} "
.\"
.SH NAME
.PP
{{.CommandPath}} - {{.Short}}
.\"
{{- if .Runnable -}}
.SH SYNOPSIS
.PP
\fB{{.UseLine}}\fP
.\"
{{ end -}}
{{ if .Long -}}
.SH DESCRIPTION
.PP
.PP {{ .Long }}
{{ end -}}
.\"
{{ if .HasAvailableSubCommands -}}
.SH SUB-COMMANDS
{{ range $index, $subcmd := .Commands }}
{{ if $subcmd.IsAvailableCommand }}
.IP \fB{{ $subcmd.Name }}\fP
{{ $subcmd.Short }}
{{ end -}}
{{ end -}}
{{ end -}}
{{ if .HasAvailableFlags -}}
.SH OPTIONS
{{ range $index, $flag := . | getFlags -}}
.IP "\fB{{ if and ($flag.Shorthand) (not $flag.ShorthandDeprecated) -}}\-{{ $flag.Shorthand }}, {{ end }}\-\-{{ $flag.Name }} {{ if $flag.NoOptDefVal }}\fI(default={{ $flag.NoOptDefVal }})\fP{{end}}"
{{ $flag.Usage | replace "\n" "" }}
{{ end -}}
{{ end -}}
{{ if .Example -}}
.SH EXAMPLE
{{ .Example }}
{{ end -}}
