# SPDX-FileCopyrightText: Copyright 2024 Prasad Tengse
# SPDX-License-Identifier: MIT
#
# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Bug Report
description: Report a bug
title: "[BUG] -  "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please report security issues privately via [Security Advisories](https://github.com/tprasadtp/go-keychain/security/advisories).

  # version
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        - Version of the module or commit hash
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: "Platform/Operating System"
      multiple: false
      options:
        - "Windows"
        - "Linux"

  - type: textarea
    id: runtime
    attributes:
      label: Runtime/Environment
      description: |
        Provide runtime environment details. Like systemd version
        or container runtime version or Kubernetes version etc.
    validations:
      required: true

  - type: textarea
    id: more-info
    attributes:
      label: Detailed Description
      description: |
        Please provide detailed description of the bug. Possibly with debug logs.
    validations:
      required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct & PII Redaction
      description: |
        By submitting this issue, you agree to follow code of conduct for this repository.
        In case the repository is missing code of conduct, Contributor Covenant code of conduct applies.
        Please also ensure that you remove or redact any sensitive personally identifying information
        like IP addresses and secrets like your API keys from logs and report included here.
      options:
        - label: I have verified that this feature request is not a duplicate.
          required: true
        - label: I agree to follow this project's Code of Conduct.
          required: true
        - label: I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.
          required: true
