name: dependency-review
on:
  pull_request:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Review-Dependency
        uses: actions/dependency-review-action@v3
