name: dependency-review
on:
  pull_request:
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
      - uses: actions/dependency-review-action@v2 # ratchet:exclude
