name: test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
      - uses: actions/setup-go@v3 # ratchet:exclude
        with:
          cache: true
      - name: Run tests
        run: |
          env
          go test ./...
